[package]
name = "watchexec"
version = "1.1.0"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]
description = "Executes commands in response to file modifications"
documentation = "https://github.com/mattgreen/watchexec"
homepage = "https://github.com/mattgreen/watchexec"
repository = "https://github.com/mattgreen/watchexec"
readme = "README.md"
keywords = ["watcher", "inotify", "fsevents", "kqueue"]
license = "Apache-2.0"

[profile.release]
lto = true

[dependencies]
glob = "0.2.11"
log = "0.3.6"
notify = "2.6.3"

[dependencies.clap]
version = "2.14"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.3.5"
default-features = false
features = []
